apiVersion: v1
kind: Service
metadata:
  name: server-clusterip-service
spec:
  type: ClusterIP
  selector:
    component: server 
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      component: server 
  template:
    metadata:
      labels:
        component: server 
    spec:
      containers:
      - name: server 
        image: hcc0429/randomcat-server
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        resources:
          requests:
            cpu: '300m'
            memory: '128M'
          limits:
            cpu: '600m'
            memory: '512M'
        env:
          - name: REDIS_ADDR
            value: redis-clusterip-service:6379
          
          - name: USE_CACHE
            value: "TRUE"
          
          - name: DATABASE_NAME
            value: randomcat

          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: database
                key: DATABASE_URL
          - name: CLOUDINARY_URL
            valueFrom:
              secretKeyRef:
                name: cloudinary
                key: CLOUDINARY_URL
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: server-horizontal-pod-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
      

