name: Change GKE Configurations
on:
  push:
    branches:
      - 'main'
    paths:
      - 'kubernetes/**'

env:
  GKE_CLUSTER: randomcat-cluster1
  GKE_REGION: asia-east1

jobs:
  config-gke:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: gcloud auth
        id: auth
        uses: google-github-actions/auth@v1
        with: 
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      
      - name: get credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_REGION }}

      - name: apply kubernetes setting
        if: steps.changes.outputs.kubernetes == 'true' 
        run: |
          kubectl apply -f kubernetes
