name: data-sync
on:
  schedule: 
    - cron: "0 0 */3  * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    env:
      USE_CACHE: FALSE
    steps:
      - name: setup go
        uses: actions/setup-go@v4

      - name: checkout
        uses: actions/checkout@v3

      - name: cron job
        working-directory: server/internal/cron/
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        run: go run cron.go
