name: Build and Deploy to GKE
on:
  push:
    branches:
      - 'main'
    paths:
      - 'client/**'
      - 'server/**'

env:
  PROJECT_ID : ${{secrets.GKE_PROJECT_ID}}
  GKE_CLUSTER: randomcat-cluster1
  GKE_REGION: asia-east1

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: change detecter
        id: changes
        uses: dorny/paths-filter@v2
        with: 
          filters: |
            client: 
              - client/**
            server:
              - server/**

      - name: login to docker
        uses: docker/login-action@v2
        with:
          username: israndomcat
          password: ${{ secrets.DOCKER_PASSWORD}}
      
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: build and push client
        if: steps.changes.outputs.client == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: israndomcat/randomcat-client
      
      - name: build and push server
        if: steps.changes.outputs.server == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: israndomcat/randomcat-server

      - name: gcloud auth
        id: auth
        uses: google-github-actions/auth@v1
        with: 
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      
      - name: get credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_REGION }}

      - name: rollout update
        run: |
          kubectl rollout restart deploy server-deployment
          kubectl rollout restart deploy client-deployment
