# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: List contents of working directory
         run: ls -R

      #- name: navigate directory into server
      #  working-directory: randomcat/server
      #  run: echo "hello world"
